---
ensure_folders:
  - "~/.config"
  - "~/.config/nvim"
  - "~/.config/htop"
  - "~/.config/fish"
  - "~/.npm-global"
  - "~/.gnupg"
  - "~/Desktop/config/dotfiles/.vim/autoload"
  - "~/.local/bin"

initial_configs:
  # Files
  - .nanorc
  - .vimrc
  - .config/starship.toml
  # Folders
  - .config/fish
  - .nano
  - .vim
  - .config/nvim
  - .config/htop

shared_packages:
  # Required
  - ansible
  # Most common terminal stuffs
  - fish
  - git
  - git-lfs
  # Addinational terminal stuffs
  - nano
  - neovim
  - mosh
  - tmux
  - htop
  # Optional, but common utilities
  - rsync
  - rclone
  - curl
  - wget
  - gpg
  - git-cola
  - neofetch
  # Programming Language
  - php
  # Package managers
  - yarn
  - composer
  # PL essentials
  - gradle
  # Addinational tools
  - podman
  - qemu
  # Build tools
  - cmake
  - unzip
  # Necessary tools
  - ffmpeg
