---
initial_configs:
  # Files
  - .gitconfig
  - .gitignore
  - ~/.gnupg/gpg.conf
  # Folders
  - .config/autostart
  - nfancurve

shared_packages:
  # Necessary tools
  - imagemagick

fnm_versions:
  - 12.22.1
  - 14.17.0

npm_modules:
  # Necessary tools
  - node-gyp
  # Local Server stuffs
  - http-server
  # npm tools
  - npm-check-updates
  - typesync
  # Mobile dev
  - cordova
  # - expo-cli
  # ReasonML
  - bs-platform
  - esy

pip_modules:
  - virtualenv
  - jupyterlab
  - notebook
  - labelme
  - psrecord

# Oni2 Extensions
oni2_extensions:
  # Formatters
  - esbenp.prettier-vscode
  # Linters
  - dbaeumer.vscode-eslint
  # Programming Language
  - ms-python.python
  - golang.go
