---
- name: Include Linux Common playbook
  import_playbook: ../../../common/os/linux/playbook.yml

- name: Linux Server Playbook
  hosts: all
  gather_facts: yes
  become: yes
  remote_user: root
  vars_files:
    - ../shared/vars.yml
    - vars.yml

  environment:
    NPM_CONFIG_PREFIX: "~/.npm-global"
    PATH: "/usr/local/bin:$HOME/.local/bin:{{ ansible_env.PATH }}"

  pre_tasks:
    # Pre-installation steps
    - import_tasks: ../../../common/os/shared/pre-task.yml
    - import_tasks: ../shared/pre-task.yml

  tasks:
    # Installation
    - import_tasks: ../../../common/os/linux/_manjaro.yml
      when: ansible_facts['os_family'] == 'Archlinux'
    - import_tasks: ../../../common/os/linux/_debian.yml
      when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Pop!_OS'
    # Some of codes we're used from
    # https://blog.ssdnodes.com/blog/secure-ansible-playbook/
    - import_tasks: tasks.yml
