---
- name: Setting default shell
  become: yes
  become_user: root
  user:
    name: "{{ item }}"
    shell: /usr/bin/fish
  loop:
    - root
    - "{{ USER }}"
  register: fish_set_default
  until: fish_set_default is successful

- name: Hide some applications
  become: yes
  become_user: root
  lineinfile:
    path: "/usr/share/applications/{{ item }}.desktop"
    insertafter: "^Name= "
    line: NoDisplay=true
  loop:
    - nvim
    - openjdk-14-java
    - openjdk-14-policytool
    - groovyConsole
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Pop!_OS'
