---
# Homebrew taps
brew_taps:
  - heroku/brew
  - dprint/dprint
  - homebrew/cask-fonts
  - adoptopenjdk/openjdk
  - octave-app/octave-app
  - marblenix/onivim2

# Homebrew packages
brew_packages:
  - pyqt
  # PL Essentials
  - rust-analyzer
  - cocoapods
  # Other desktop tools
  - dprint
  - heroku
  # Tools / Dependencies
  - watchman

brew_cask_packages:
  # macOS QuickLook plugins
  - qlcolorcode
  - qlstephen
  - qlmarkdown
  - qlimagesize
  # Fonts
  - font-fira-code
  # Utilities
  - app-cleaner
  - macupdater
  - kdiff3
  - android-file-transfer
  - browserstacklocal
  - anydesk
  - balenaetcher
  - cyberduck
  # Screen Capture
  - obs
  # Management
  - ganttproject
  # Firewall
  - lulu
  # Browsers
  - firefox
  - google-chrome
  # Most needed desktop apps
  - vlc
  - notion
  # AI/ML
  - octave-app
  # Git App
  - gitkraken
  # Download managers
  - 4k-video-downloader
  - folx
  # Development tools
  - datagrip
  # HTTP/GraphQL clients
  - postman
  - insomnia
  - altair-graphql-client
  # Editors
  - sublime-text
  # - onivim2-nightly
  - visual-studio-code
  - android-studio
  - webstorm
  # Gaming
  - steam

brew_cask_packages_root:
  # - malwarebytes
  - adguard
  - adoptopenjdk/openjdk/adoptopenjdk11
  - anaconda
  - cloudflare-warp
  - docker
  # - vmware-fusion # M1 Support not available, see https://communities.vmware.com/t5/VMware-Fusion-Discussions/vmware-fusion-on-m1-goal/m-p/2837097#M173227
  # - anka-virtualization # Waiting for M1 support
  - virtualbox
